#!/bin/bash

# CCA 课后课选课系统 - 快速测试指南
# Quick Test Guide for CCA Planning System

echo "======================================"
echo "CCA 课后课选课系统 - 功能测试"
echo "======================================"
echo ""

echo "📋 已完成的优化功能："
echo ""
echo "✅ 1. 跨页面浮动规划框"
echo "   - 实时显示选择进度和周计划"
echo "   - 可拖拽、可最小化"
echo "   - 移动端自动定位到底部"
echo ""
echo "✅ 2. 精英项目智能过滤"
echo "   - 根据年级自动隐藏不可选项目"
echo "   - 整个类别无可选项时隐藏卡片"
echo "   - 时间段冲突自动检测"
echo ""
echo "✅ 3. 响应式卡片布局"
echo "   - 手机：1列"
echo "   - 平板：2列"
echo "   - 桌面：3列"
echo "   - 宽屏：4列"
echo ""
echo "✅ 4. 知识板块图标系统"
echo "   - 🎯 技能类  🏆 竞赛类  📚 学术支持"
echo "   - 👥 俱乐部  🔍 体验类  ⚽ 体育类"
echo "   - 🎨 艺术类  🎵 音乐类  🔬 STEM类"
echo ""

echo "======================================"
echo "🧪 测试步骤："
echo "======================================"
echo ""
echo "1️⃣  打开浏览器访问："
echo "   file:///Users/ryantang/Documents/harrow-portal/cca-planning.html"
echo ""
echo "2️⃣  选择年级（建议选择 G6 或 G9）"
echo "   → 观察右侧浮动规划框出现"
echo "   → 观察精英项目卡片的变化"
echo ""
echo "3️⃣  选择精英项目（如：足球中学）"
echo "   → 观察浮动框显示精英项目列表"
echo "   → 观察周计划显示占用的天数"
echo ""
echo "4️⃣  进入CCA选课步骤"
echo "   → 观察被占用的天数显示警告"
echo "   → 选择其他天数的CCA课程"
echo "   → 观察知识板块图标显示"
echo ""
echo "5️⃣  查看浮动规划框"
echo "   → 实时更新的周计划"
echo "   → 统计信息（精英项目数、CCA课程数）"
echo "   → 尝试拖拽和最小化"
echo ""
echo "6️⃣  移动端测试"
echo "   → 调整浏览器窗口到手机尺寸"
echo "   → 观察浮动框定位到底部"
echo "   → 观察卡片变为单列布局"
echo ""

echo "======================================"
echo "🎯 重点测试场景："
echo "======================================"
echo ""
echo "场景1：年级过滤"
echo "  - 选择 G1：应该看不到无主乐队、辩论队"
echo "  - 选择 G6：应该看到所有中学项目"
echo "  - 选择 G9：应该看到中文数学支持"
echo ""
echo "场景2：时间冲突"
echo "  - 选择足球（中学）：周一、周二、周四被占用"
echo "  - 选择篮球（中学）：周二、周四被占用"
echo "  - 同时选择两个：应该看到冲突警告"
echo ""
echo "场景3：定制时间项目"
echo "  - 选择钢琴：不占用CCA时段"
echo "  - 选择高尔夫：不占用CCA时段"
echo "  - 可以正常选择所有天数的CCA"
echo ""
echo "场景4：知识板块图标"
echo "  - 滑板：🎯 技能类"
echo "  - 袋鼠数学：🏆 竞赛类"
echo "  - 物理支持：📚 学术支持"
echo "  - 学生会：👥 俱乐部"
echo ""

echo "======================================"
echo "📱 移动端测试要点："
echo "======================================"
echo ""
echo "✓ 浮动框定位到底部"
echo "✓ 可向上滑动查看内容"
echo "✓ 精英项目卡片单列显示"
echo "✓ 周课程表单列显示"
echo "✓ 按钮全宽显示"
echo "✓ 进度指示器可横向滚动"
echo ""

echo "======================================"
echo "⚠️  已知限制："
echo "======================================"
echo ""
echo "1. Excel数据更新需要手动操作"
echo "   → 请提供Excel文件内容或截图"
echo "   → 我会帮您更新课程数据"
echo ""
echo "2. 浮动框拖拽仅支持桌面端"
echo "   → 移动端固定在底部"
echo ""
echo "3. 需要现代浏览器支持"
echo "   → Chrome 90+, Safari 14+, Firefox 88+"
echo ""

echo "======================================"
echo "📚 相关文档："
echo "======================================"
echo ""
echo "详细说明：CCA_OPTIMIZATION_GUIDE.md"
echo "数据配置：scripts/cca-data.js"
echo "样式文件：styles/floating-planner.css"
echo "逻辑文件：scripts/floating-planner.js"
echo ""

echo "======================================"
echo "🚀 准备就绪！"
echo "======================================"
echo ""
echo "请在浏览器中打开 cca-planning.html 开始测试"
echo ""
echo "如有问题，请查看 CCA_OPTIMIZATION_GUIDE.md"
echo "或联系技术支持团队"
echo ""
